blank_issues_enabled: false
contact_links:
  - name: Question and help request
    url: https://github.com/acmelab-ua/FEPX/discussions
    about: Ask questions and discuss with other community members
